<html>


    <head>
        <meta charset="utf-8">
        <title>Privacy Policy</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="icon" href="{{asset('public/images/LOGO_ICON_PNG.png')}}" type="image/gif" sizes="16x16">
    </head>

    <body>

        <div dir="ltr">
            <div style="box-sizing:border-box;margin-bottom:55px;color:rgb(58,58,58);font-family:&quot;Work Sans&quot;,sans-serif;font-size:19px;text-align:center">
                <div style="box-sizing:border-box;margin-bottom:55px">
                    <h1 style="box-sizing:border-box;margin:0px 0px 17.5px;line-height:1.2;letter-spacing:0px">Privacy Policy</h1>
                </div>
                <div style="box-sizing:border-box;margin-bottom:0px;text-align:start">
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><span style="box-sizing:border-box">Pinned values the privacy of individuals who use our websites and related services.</span></p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">In this Policy, “Pinned”, “we” or “us” refers to Brendi.lv, a company established in Riga, Latvia. Our support,&nbsp;<span style="box-sizing:border-box">p</span><span style="box-sizing:border-box">rivacy, term compliance office&nbsp;</span>and
                        investment office are located in London, England. All Pinned products will be distributed from Riga, Latvia.</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">We take privacy seriously and we have adopted technical and organizational measures designed to protect your data. This privacy policy (the “Policy”) explains how we use, collect, and share information from users of our Services. If you are
                        located in the European Economic Area (“EEA”), this Policy informs you of your choices and our practices in relation to your Personal Information (as defined below).</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><span style="box-sizing:border-box">For the purpose of this Policy, “</span>Personal&nbsp;Information<span style="box-sizing:border-box">” means any information relating to an identified or identifiable individual. This includes Personal Information collected and processed by us when you access our websites (including&nbsp;</span>
                        <a
                            href="http://pinned.eu" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://pinned.eu&amp;source=gmail&amp;ust=1606984736359000&amp;usg=AFQjCNHxHDNbtJ_9q5hIbE9rpBnyE2obTw">pinned.eu</a><span style="box-sizing:border-box">) (the “</span>Website<span style="box-sizing:border-box">”), the Pinned app, and the services related to them (collectively, together with the Website, Pinned app, and the related services, our “</span>Services
                        <span
                            style="box-sizing:border-box">”). This Policy describes the Personal Information that we collect from you on our Services, how we use and disclose such Personal Information, your rights and choices with respect to your information, and how you can contact us if
                            you have any questions or concerns. Beyond this Policy, your use of our Services is also subject to our&nbsp;</span><a href="https://popl.co/pages/terms-of-use" style="box-sizing:border-box;text-decoration-line:none;background-color:transparent;border-bottom:1px solid currentcolor;padding-bottom:1px"
                                                                                                                                               target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://popl.co/pages/terms-of-use&amp;source=gmail&amp;ust=1606984736359000&amp;usg=AFQjCNHmsvx0xmTmoxcsn5RjCSX_rR5Wgw">Terms of<span style="box-sizing:border-box">&nbsp;</span></a>
                        <a
                            href="https://popl.co/pages/terms-of-use" style="box-sizing:border-box;text-decoration-line:none;background-color:transparent;border-bottom:1px solid currentcolor;padding-bottom:1px" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://popl.co/pages/terms-of-use&amp;source=gmail&amp;ust=1606984736359000&amp;usg=AFQjCNHmsvx0xmTmoxcsn5RjCSX_rR5Wgw">Use</a><span style="box-sizing:border-box">.</span></p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><strong style="box-sizing:border-box">The personal information we collect</strong></p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><span style="box-sizing:border-box">We may collect and use the following Personal Information about you.&nbsp;</span>Personal Information You Provide to Us.</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">Communications with us. When you contact us directly, we may receive additional information about you. For example, when you contact us for customer support, we may receive your name, email address, the content of a message or attachments
                        that you may send to us, and other information you choose to provide. If you subscribe to our newsletter, then we will collect certain information from you, such as your email address. When we send you emails, we may track whether you
                        open them to learn how to deliver a better customer experience and improve our Services.</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">Transaction-related information.<strong style="box-sizing:border-box"><span style="box-sizing:border-box">&nbsp;</span></strong><span style="box-sizing:border-box">When you purchase something on the Website or the Pinned app, you may be asked to provide us with your information such as your name, phone number, and address. Your payment-related information, such as credit card, or other financial information, is collected by our third party payment processors on our behalf.</span></p>
                    <p
                        style="box-sizing:border-box;margin:0px 0px 19.4444px">Service-related information. When you use our Services, you can choose to provide certain Personal Information, including your contact information, social media links, and location.</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">Product reviews.&nbsp;When you reply to our request to review and rate your experience with our Services, you may provide us with additional information about you. The information we collect from you varies depending on the review but
                        typically includes your name, the Service you used, and your opinion about the Service.</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><strong style="box-sizing:border-box">Personal information we collect when you use our services</strong></p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">Location information. When you use our Services, we may infer your general location information, for example, when you use the Pinned app.</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">Device information. We receive information about the device and software you use to access our Services, including IP address, web browser type, and operating system version.</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">Usage information. To help us understand how you use our Services and to help us improve them, we automatically receive information about your interactions with our Services, like the pages or other content you view, the searches you conduct,
                        purchases you make, and the dates and times of your visits.</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">Information from Cookies and Similar Technologies.&nbsp;We and third party partners collect Personal Information using cookies, pixel tags, or similar technologies. Our third party partners, such as analytics and advertising partners,
                        may use these technologies to collect information about your online activities over time and across different services. We may use both session cookies (which are deleted from your device after you leave the Website) and persistent
                        cookies (which remain on your device for longer or until you delete them manually). A session cookie disappears after you close your browser. A persistent cookie remains after you close your browser and may be used by your browser
                        on subsequent visits to our Services. Please review your web browser’s “Help” file to learn the proper way to modify your cookie settings. Please note that if you delete or choose not to accept cookies from our Services, you may not
                        be able to utilize the features of our Services to their fullest potential.</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><strong style="box-sizing:border-box">Personal information we receive from third parties</strong></p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">Information from third party services.&nbsp;We obtain Personal Information from third parties, such as Facebook, Snapchat, YouTube, when you click on third party buttons or beacons (such as Facebook “like” or “share” buttons, or embedded
                        YouTube video) on our Website. If you choose to link our Services to a third party account, such as Facebook, Instagram, or Snapchat, we may receive information about you, including your profile information and your photo. If you wish
                        to limit the information available to us, you should visit the privacy settings of your third party accounts to learn about your options. If we combine or associate information from other sources with Personal Information that we collect
                        through our Services, we will treat the combined information as Personal Information in accordance with this Policy.</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><strong style="box-sizing:border-box">How we use<span style="box-sizing:border-box">&nbsp;</span></strong><strong style="box-sizing:border-box">the personal information</strong></p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">Communicating with you.<span style="box-sizing:border-box">&nbsp;</span>We may use your email address or other Personal Information we collect on our Services as necessary to contact you for administrative purposes such as to provide services
                        and information that you request, respond to comments and questions, and otherwise provide customer support.</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">Understanding usage and improving the Services.&nbsp;We use your Personal Information that we collect through our Services to analyze trends and statistics, and to improve and enhance our Services. From time to time, we may ask you to
                        participate in surveys we conduct which are in our legitimate interest because they help us understand our userbase and improve our Services. If you participate, we process your registration information and any other information collected
                        through the survey questions. We may use your email address and other Personal Information to send marketing communications related to our Services. Generally, you have the ability to opt-out of receiving any promotional communications
                        as described below under Your Rights and Choices. Where required under applicable law, we will only send you promotional emails with your opt-in consent. We may use your usage information and other Personal Information to develop and
                        provide you with promotional and advertising materials that may be relevant, valuable or otherwise of interest to you.</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">Providing the Services and personalizing your experience.&nbsp;We may use your Personal Information to provide and maintain our Services, including to facilitate transactions and payments or to enable you to connect to third party services
                        or applications. When doing so, we may use your Personal Information to personalize your experience on our Services such as by providing tailored content and recommendations.</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">Legal obligation and Compliance.&nbsp;We use your Personal Information to find and prevent fraud, respond to trust and safety issues that may arise, and for compliance purposes, including enforcing our Terms of Service or other legal rights,
                        or as may be required by applicable laws and regulations or requested by any judicial process or governmental agency.</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><strong style="box-sizing:border-box">How do we use cookies</strong></p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><span style="box-sizing:border-box">Cookies are small files of letters and numbers that we store on your browser or the hard drive of your computer.&nbsp;</span>Pixel tags and web beacons are tiny graphic images placed on web pages or
                        in emails that allow us to determine whether you have performed a specific action. When you access these pages or open or click an email, the pixel tags and web beacons generate a notice of that action. These tools allow us to measure
                        response to our communications and improve our Website and Services.&nbsp;</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><span style="box-sizing:border-box">We use cookies, web beacons, pixel tags, and similar technologies (collectively “</span>Cookies<span style="box-sizing:border-box">”) to collect information about your browsing activities and to distinguish you from other users of our Services. This aids your experience when you use our Services and also allows us to improve the functionality of our Services. When you use our Services, we collect certain information by automated means, using technologies such as Cookies and browser analysis tools. In many cases, the information we collect using Cookies and other tools is used in a non-identifiable way, without any reference to personal data. We may use Cookies to make our Website usage more efficient and to tailor your browsing preferences and improve the functionality of our Website. Cookies can be used for performance management, collecting information on how our Website is being used for analytics purposes. They can also be used for functionality management, enabling us to make the user’s visit more efficient by, for example, remembering language preferences, passwords and log-in details.&nbsp;</span>Below
                        is an overview of the types of Cookies that we and third parties may use to collect Personal Information. For more information about cookies, and how to disable cookies, visit <a href="http://www.allaboutcookies.org" target="_blank"
                                                                                                                                                                                                        data-saferedirecturl="https://www.google.com/url?q=http://www.allaboutcookies.org&amp;source=gmail&amp;ust=1606984736359000&amp;usg=AFQjCNGe3mvgPZnlioF9iZJ3JXn1-1_A4Q">http://www.allaboutcookies.org</a><wbr>.</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><strong style="box-sizing:border-box">If you are located in the European Economic Area</strong></p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">If you are located in the European Economic Area, we only process your Personal Information when we have a valid “legal basis”, including when:</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">You have consented to the use of your Personal Information, for example to send you marketing communications or to use cookies and similar technologies.</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">Contractual necessity.&nbsp;We need your Personal Information to provide you with our Services, for example to respond to your inquiries.</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">Compliance with a legal obligation.&nbsp;We have a legal obligation to use your Personal Information, for example to comply with tax and accounting obligations.</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">Legitimate interests.&nbsp;We or a third party have a legitimate interest in using your Personal Information. In particular, we have a legitimate interest in using your Personal Information for product development and internal analytics
                        purposes, and otherwise to improve the safety, security, and performance of our Services. We only rely on our or a third party’s legitimate interests to process your Personal Information when these interests are not overridden by your
                        rights and interests.</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><strong style="box-sizing:border-box">How we share the personal information</strong></p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><span style="box-sizing:border-box">Except as described in this Policy, we will not disclose your information that we collect on our Services to third parties without your consent. We may disclose information to third parties if you consent to us doing so, as well as in the following circumstances.&nbsp;</span>We
                        may share any information we receive with our corporate affiliates for any of the purposes described in this Policy. We may share any information we receive with vendors and service providers retained in connection with the provision
                        of our Services.&nbsp;<span style="box-sizing:border-box">We use analytics services such as Google Analytics to collect and process certain analytics data. These services may also collect information about your use of other websites, apps, and online resources. You can learn more about Google’s practices by visiting&nbsp;</span>
                        <a
                            href="https://www.google.com/policies/privacy/partners/" rel="noopener noreferrer" style="box-sizing:border-box;text-decoration-line:none;background-color:transparent;border-bottom:1px solid currentcolor;padding-bottom:1px" target="_blank"
                            data-saferedirecturl="https://www.google.com/url?q=https://www.google.com/policies/privacy/partners/&amp;source=gmail&amp;ust=1606984736359000&amp;usg=AFQjCNHiPy5f2u6fG3jPvY-lVl5RNR8h0g">google.com/policies/<wbr>privacy/partners/</a><span style="box-sizing:border-box">&nbsp;.&nbsp;</span>We may work with third party advertising partners to show you ads that we think may interest you. Some of our advertising partners
                        are members of the Network Advertising Initiative (<a href="http://optout.networkadvertising.org/" rel="noopener noreferrer" style="box-sizing:border-box;text-decoration-line:none;background-color:transparent;border-bottom:1px solid currentcolor;padding-bottom:1px"
                                                                              target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://optout.networkadvertising.org/&amp;source=gmail&amp;ust=1606984736359000&amp;usg=AFQjCNESbfodUFXRZOH316SBx0U0rNeQDg">networkadvertising.org</a>&nbsp;) or
                        the Digital Advertising Alliance (<a href="http://optout.aboutads.info" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://optout.aboutads.info&amp;source=gmail&amp;ust=1606984736359000&amp;usg=AFQjCNEX9u4HAWgowQvfCSQSep0yNRLT3A">optout.aboutads.info</a>)
                        . If you do not wish to receive personalized ads, please visit their opt-out pages to learn about how you may opt out of receiving web-based personalized ads from member companies. You can access any settings offered by your mobile
                        operating system to limit ad tracking, or you can install the AppChoices mobile app to learn more about how you may opt out of personalized ads in mobile apps. We may access, preserve, and disclose your information if we believe
                        doing so is required or appropriate to: (a) comply with law enforcement requests and legal process, such as a court order or subpoena; (b) respond to your requests; or (c) protect your, our, or others’ rights, property, or safety.
                        For the avoidance of doubt, the disclosure of your information may occur if you post any objectionable content on or through our Services. We may transfer your information to service providers, advisors, potential transactional
                        partners, or other third parties in connection with the consideration, negotiation, or completion of a corporate transaction in which we are acquired by or merged with another company or we sell, liquidate, or transfer all or a
                        portion of our assets. Any information related to your experience with our Service that you provide via our review mechanism may be displayed for promotional purposes. We may also disclose your information with your permission.</p>
                    <p
                        style="box-sizing:border-box;margin:0px 0px 19.4444px"><strong style="box-sizing:border-box">Your rights and choices</strong></p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">For Ambassadors, certain information such as your user name may always be publicly available to others, and other information may be made publicly available to others by default. You can revise, modify, or delete your account information.
                        You can unsubscribe from our promotional emails via the link provided in the emails. Even if you opt-out of receiving promotional messages from us, you may continue to receive administrative messages from us. You can block Cookies
                        by setting your internet browser to block some or all the Cookies. However, if you use your browser settings to block all Cookies (including essential Cookies) you may not be able to access all or parts of our Services.&nbsp;
                        <span
                            style="box-sizing:border-box">We do not process web browser Do Not Track signals. To learn more about browser tracking signals and Do Not Track please visit</span><a href="http://www.allaboutdnt.org/" rel="noopener noreferrer" style="box-sizing:border-box;text-decoration-line:none;background-color:transparent;border-bottom:1px solid currentcolor;padding-bottom:1px"
                            target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://www.allaboutdnt.org/&amp;source=gmail&amp;ust=1606984736360000&amp;usg=AFQjCNGtevtgyVlKdhgSp_KGqfUfmfmgzg"><span style="box-sizing:border-box">&nbsp;</span>http://www.allaboutdnt.<wbr>org</a>
                        <span
                            style="box-sizing:border-box">.</span>
                    </p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><strong style="box-sizing:border-box">Your European privacy rights</strong></p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">If you are located in the European Economic Area, you have the additional rights described below. You may request access to and receive information about the Personal Information we maintain about you, update and correct inaccuracies
                        in your Personal Information, restrict or object to the processing of your Personal Information, have the information anonymized or deleted, as appropriate, or exercise your right to data portability to easily transfer your Personal
                        Information to another company. In addition, you also have the right to lodge a complaint with a supervisory authority, including in your country of residence, place of work or where an incident took place. You may withdraw any
                        consent you previously provided to us regarding the processing of your Personal Information, at any time and free of charge. We will apply your preferences going forward and this will not affect the lawfulness of the processing
                        before you withdrew your consent. You may exercise these rights by contacting us using the contact details at the end of this Policy. Before meeting your request, we may ask you to provide reasonable information to verify your
                        identity. Please note that there are exceptions and limitations to each of these rights, and that while any changes you make will be reflected in active user databases instantly or within a reasonable period of time, we may retain
                        information for backups, archiving, prevention of fraud and abuse, analytics, satisfaction of legal obligations, or where we otherwise reasonably believe that we have a legitimate reason to do so.</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><strong style="box-sizing:border-box">European visitors</strong></p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><span style="box-sizing:border-box">If you are located in the European Economic Area, we will comply with applicable EEA data protection law when transferring your Personal Information outside of the EEA. We may transfer your Personal Information to countries which have been found to provide adequate protection by the EU Commission, use contractual protections for the transfer of Personal Information, transfer to recipients who have adopted Binding Corporate Rules, or rely on an appropriate legal derogation. For more information about how we transfer outside of the EEA, or to obtain a copy of the contractual safeguards we use for such transfers, you may contact us using the contact details given below.</span></p>
                    <p
                        style="box-sizing:border-box;margin:0px 0px 19.4444px"><strong style="box-sizing:border-box">International visitors</strong></p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><span style="box-sizing:border-box">If you choose to use our Services from regions of the world with laws governing data collection and use that may differ from European law, then please note that you are transferring your Personal Information outside of those regions to the Latvia for storage and processing, which does not have the same data protection laws as your jurisdiction.&nbsp;</span></p>
                    <p
                        style="box-sizing:border-box;margin:0px 0px 19.4444px"><span style="box-sizing:border-box"><strong style="box-sizing:border-box">Third parties</strong></span></p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">Our Services may contain links to other websites, products, or services that we do not own or operate. We are not responsible for the privacy practices of these third parties. Please be aware that this Policy does not apply
                        to your activities on these third party services or any information you disclose to these third parties. We encourage you to read their privacy policies before providing any information to them.</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><strong style="box-sizing:border-box">Retention</strong></p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">We take measures designed to delete your Personal Information or keep it in a form that does not permit identifying you when this information is no longer necessary for the purposes for which we process it, unless we are required
                        by law to keep this information for a longer period. When determining the specific retention period, we take into account various criteria, such as the type of service provided to you, the nature and length of our relationship
                        with you, and mandatory retention periods provided by law and the statute of limitations.</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><strong style="box-sizing:border-box">Children’s privacy</strong></p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><span style="box-sizing:border-box">We do not knowingly collect, maintain, or use Personal Information from children under 14 years of age, and no part of our Services are directed to children. If you learn that a child has provided us with Personal Information in violation of this Policy, then you may alert us at&nbsp;<a href="mailto:info@pinned.eu" target="_blank">info@pinned.eu</a> .</span></p>
                    <p
                        style="box-sizing:border-box;margin:0px 0px 19.4444px"><strong style="box-sizing:border-box">Security</strong></p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">We make reasonable efforts designed to protect your information by using physical and electronic safeguards to improve the security of the information we maintain. However, as no electronic transmission or storage of information
                        can be entirely secure, we can make no guarantees as to the security or privacy of your information.</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><strong style="box-sizing:border-box">Changes to this policy</strong></p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><span style="box-sizing:border-box">We will post any adjustments to this Policy on this page, and the revised version will be effective when it is posted. If we materially change the ways in which we use or share Personal Information previously collected from you through our Services, we will notify you through our Services, by email, or other communication.</span></p>
                    <p
                        style="box-sizing:border-box;margin:0px 0px 19.4444px"><span style="box-sizing:border-box"><strong style="box-sizing:border-box">Contact information</strong></span></p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px">Pinned welcomes your questions or comments regarding the Terms:</p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><span style="box-sizing:border-box">Brendi.lv Maskavas 222A-18, LV-1019</span></p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><span style="box-sizing:border-box">Email Address: <a href="mailto:info@pinned.eu" target="_blank">info@pinned.eu</a> Telephone number: +37127774378</span></p>
                    <p style="box-sizing:border-box;margin:0px 0px 19.4444px"><a href="http://pinned.eu" target="_blank" data-saferedirecturl="https://www.google.com/url?q=http://pinned.eu&amp;source=gmail&amp;ust=1606984736360000&amp;usg=AFQjCNEr-pjH2dHkf_WQ3RUYT01JsY3cBQ">pinned.eu</a></p>
                    <p
                        style="box-sizing:border-box;margin:0px 0px 19.4444px"><span style="box-sizing:border-box">[Re: Privacy Compliance Officer]</span></p>
                </div>
                <font color="#888888">
                <h1 style="box-sizing:border-box;margin:0px 0px 17.5px;line-height:1.2;letter-spacing:0px">&nbsp;<span style="font-size:19px;font-weight:normal;color:rgb(34,34,34)">&nbsp;</span><br></h1>
                </font>
            </div>
        </div>
    </body>
</html>